baseURL = 'https://badia.com/'
languageCode = 'en-us'
title = 'Ann Badia'
theme = 'ananke'
defaultContentLanguage = "en"

# Author info
[author]
  name = "Ann Badia"
  email = "badiaann@gmail.com"

# Menu navigation
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 3